### ISSUE TITLE
Cursor jumping to beginning

### ISSUE THREAD

**Issue by saanderson1987** [raphasilvac/react-simple-contenteditable#3]
Hello,

I am using your module to enable editing of a fill in the blank worksheet. The reason I must use a content editable element is because I want the text of the problem to wrap. For example, if a problem has one blank, it divides the text into three sections the part before the blank, the blank, and the part after. If I were to represent the outer two as separate `div`s (or input fields), then the text would not wrap like a paragraph. Instead, I must have a single contenteditable  `div` that contains an input field for the blank and free text on either side. 

The text is wrapping like I want it, but when I type text in the contenteditable field, the cursor jumps to the beginning. I don't understand why because I tried your example and it works perfectly. My implementation is a bit more complicated, but it appears essentially the same.

Here is my render function that uses `<ContentEditable />` : 

```javascript
  render() {
    const textPieces =
      <div className='new-form-text-pieces'>
        {
          this.props.problem.textPieces.map( (textPiece, idx) => {
            if (textPiece.blank) {
              return (
                  <div data-blank={true} className='blank' key={ textPiece.id } style={{display: 'inline'}}>
                    <input
                      placeholder="Answer blank"
                      className='new-form-answer-input'
                      value={ this.props.problem.textPieces[idx].text }
                      onChange={ (event) => this.props.handleTextPiecesInput(this.props.problemIdx, idx, event.target.value) }
                    />
                    <button className='modify-blank remove-blank' onClick={ (event) => this.props.removeBlank(this.props.problemIdx, idx) }>-</button>

                  </div>
              );
            } else {
              let text = this.props.problem.textPieces[idx].text;
              const placeholder = idx === 0 ? 'Problem text' : '...continue text';
              // text = text === '' ? placeholder : text;
              if (text === '') {
                text = <span style={{color:'gray'}}>{placeholder}</span>;
              } else {

              }
              return (
                this.props.isTextSplit ?
                  <TextPiece
                    key={ textPiece.id }
                    problemIdx={this.props.problemIdx}
                    textPieceIdx={idx}
                    dropBlank={this.props.dropBlank}
                    moveBlank={this.props.moveBlank}
                  >
                    <div style={{display: 'inline-block', }}>{text}</div>
                  </TextPiece>
                : text

              );
            }
          })
        }
      </div>;



    return (
       this.props.isTextSplit ? textPieces :
        <ContentEditable
          html={ReactDOMServer.renderToStaticMarkup(textPieces)}
          className="my-class"
          tagName="div"
          onChange={ (event, value) => this.props.handleProblemChange(event, this.props.problemIdx, value) }
          contentEditable='plaintext-only'
        />
    );

  }
```

Here is the `onChange` function:
 ```javascript
  handleProblemChange(event, problemIdx) {
    const problems = cloneDeep(this.state.problems);
    event.target.children[0].childNodes.forEach( (textPieceNode, idx) => {
      if (textPieceNode.constructor === Text) {
        problems[problemIdx].textPieces[idx].text = textPieceNode.wholeText;
      } else {
        problems[problemIdx].textPieces[idx].text = textPieceNode.childNodes[0].value;
      }
    });
    this.setState({ problems });
  }
```
And here is the state it refers to, just to make thing clear:

```javascript
    this.state = {
      problems: [
        {
          id: shortid.generate(),
          textPieces: [
            {
              text : "Three days was simply not a(n)",
              blank : false,
              id: shortid.generate(),
            },
            {
              text : "acceptable",
              blank : true,
              id: shortid.generate(),
            },
            {
              text : "amount of time to complete such a lot of work.",
              blank : false,
              id: shortid.generate(),
            }
          ]
        }
```

Thanks so much

**Comment by DmitrySoshnikov** [comment]
In the README it's written:

> Prevent cursor jumping to the beginning of the field;

But I also see it just jumps to the beginning. Seems it's a known issue with contenteditable in ReactJS, and the recommendation is to switch to Draft.js?

**Comment by raphasilvac** [comment]
Hello guys,
First os all, thank you by the reporting.

I think it's not a react bug, "maybe" it's a contenteditable bug.

The problem here is that you are modifiing the text and repassing this new value to the component again, this way the cursor lost it's position and jumps to the begin.

This happen with input too when you change the value while you are typing, with a bit difference: in the input cursor jumps to the end (best approach).

Seems for me that you trying do something like a mask, as a mask lib I think you need control the cursor position by yourself.

The approach of this lib is really simple: 
We just check if the new value is the same of the contenteditable element, 
if this is true we not update the react component this way we avoid that the cursor 
jumps to begin.
```
  shouldComponentUpdate(nextProps, nextState) {
    const method = this.getInnerMethod();
    return nextProps.html !== this.elem[method];
  }
```

I think in the link bellow you can check better my explanation (No react, no libs, just vanilla js):
https://jsfiddle.net/z9t6uos9/4/

See the gif bellow, after 5 seconds I changed the value of contenteditable, happens the same when you use onChange, with input element happens the same too but as I said before, cursor jumps to the end.
![alt text](https://im4.ezgif.com/tmp/ezgif-4-d74d210ba0.gif)

In the contenteditable puts the cursor in the end.
In the input puts cursor in the begin.

After 5 second you will see that:
In the contenteditable cursor jumps to begin
In the input cursor jumps to the end

I would like to appologize about my english, and I wish that you understood the problem.

Draft.js is a great choice maybe they have a solution for it.

Thanks!
